apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: database
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  strategy: {}
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: my_wiki
        - name: MYSQL_PASSWORD
          value: example
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: "yes"
        - name: MYSQL_USER
          value: wikiuser
        image: mariadb
        name: database
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: database-claim0
      restartPolicy: Always
      volumes:
      - name: database-claim0
        persistentVolumeClaim:
          claimName: database-claim0
      restartPolicy: Always
status: {}
