apiVersion: v1
kind: Service
metadata:
  labels:
    app: database
  name: databasesvc
spec:
  type: ClusterIP
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    app: database
status:
  loadBalancer: {}
