apiVersion: v1
kind: Service
metadata:
  labels:
    app: mediawiki
  name: mediawiki
spec:
  type: LoadBalancer
  ports:
  - name: "8080"
    port: 8080
    targetPort: 80
  selector:
    app: mediawiki
status:
  loadBalancer: {}
