apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mediawiki
  name: mediawiki
spec:
  replicas: 1
  selector:
    matchLabels:
     app: mediawiki
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      containers:
      - image: mediawiki
        name: mediawiki
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /var/www/html/images
          name: mediawiki-claim0
      restartPolicy: Always
      volumes:
      - name: mediawiki-claim0
        persistentVolumeClaim:
          claimName: mediawiki-claim0
status: {}
